echo "script name:: $0"
echo "total variables passed:: $@"
echo "number of variables passed:: $#"
echo "previous process executed status:: $?"
echo "process ID of current script:: $$"
echo "Home directory of current user:: $HOME"
echo "Which user is running this script:: $USER"
echo "present working directory:: $PWD"
sleep 60 &
echo "process ID of last command in background:: $!"
